### ISSUE TITLE
Stripe test token fails when usage limit exceeded

### ISSUE THREAD

**Issue by jmromer** [bikeindex/bike_index#1017]
```
(Status 503) Test mode requests are temporarily disabled due to exceptionally high traffic. Please contact us via https://support.stripe.com/contact for more information if this problem persists.
Failure/Error: @approved_card_token ||= Stripe::Token.create(card: stripe_card(:visa))

Stripe::APIError:
  Test mode requests are temporarily disabled due to exceptionally high traffic. Please contact us via https://support.stripe.com/contact for more information if this problem persists.
./spec/support/stripe_helpers.rb:24:in `stripe_token_approved'
./spec/controllers/payments_controller_spec.rb:70:in `block (5 levels) in <top (required)>'
./spec/controllers/payments_controller_spec.rb:69:in `block (4 levels) in <top (required)>'
------------------
--- Caused by: ---
Faraday::ClientError:
  the server responded with status 503
  ./spec/support/stripe_helpers.rb:24:in `stripe_token_approved'
```

**Comment by sethherr** [comment]
This was happening earlier today, e.g. Pr #1011 ([this job on CircleCI](https://circleci.com/gh/bikeindex/bike_index/4692?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)). I just merged and manually deployed

**Comment by jmromer** [comment]
Are we testing against the Stripe API in automated tests intentionally? If not it might make sense to stub out or VCR those calls.

**Comment by sethherr** [comment]
We are, because I felt like having actual requests go through for money was good. Case in point, this situation!

I could be convinced with some cassettes with short expirations, or a good argument

**Comment by jmromer** [comment]
> We are

Cool — just wanted to flag the test failure in case it wasn't intentional. I don't see this becoming a recurring issue unless the number of developers working on the project increases, so I'll close for now. Cassettes with short expirations would probably be the most expedient approach.
