### ISSUE TITLE
Pure Fix make displaying as "pure_fix" in theft report

### ISSUE THREAD

**Issue by realchrisolin** [bikeindex/bike_index#1045]
https://bikeindex.org/bikes/631411

![image](https://user-images.githubusercontent.com/1288116/61344055-e5892880-a81d-11e9-8b8c-97c05c661f0a.png)

**Comment by sethherr** [comment]
In this case, the user typed that in.

I've fixed an issue related to the way manufacturers are displayed which hopefully will improve the situation (#1049).

**Comment by realchrisolin** [comment]
>In this case, the user typed that in.

Begging your pardon. I registered the bike (the owner is a friend) and did **not** type that in. The make field auto-populates when you start typing. I selected "Pure Fix" from the dropdown and "pure_fix" is what ended up entered. I'll keep this closed while we see if #1049 fixes this.

**Comment by sethherr** [comment]
That's a new and surprising issue. I'll figure out what happened.

**Comment by sethherr** [comment]
It was a caching issue! It's been fixed and I've made sure that it won't happen again.

Thanks for letting me know that the fix I'd made hadn't covered your issue 🙂
