### ISSUE TITLE
Image cropping in description field when more than one picture is uploaded.

### ISSUE THREAD

**Issue by realchrisolin** [bikeindex/bike_index#108]
See https://bikeindex.org/bikes/61448 for an example. 
![Screenshot for posterity](https://cloud.githubusercontent.com/assets/1288116/10743234/20dce9da-7c08-11e5-88ea-27c1cfde5ea3.png)

Can be worked around by right clicking on the image (in Firefox) and choosing "View Image" option

**Comment by sethherr** [comment]
Resolved.
