### ISSUE TITLE
A proper replacement for the use of Model.scoped is needed. 

### ISSUE THREAD

**Issue by digitalcake** [bikeindex/bike_index#110]
`Model.scoped` is deprecated in rails4 and as noted here http://stackoverflow.com/questions/18198963/with-rails-4-model-scoped-is-deprecated-but-model-all-cant-replace-it it will not be as simple as replacing it with `.all`

**Comment by sethherr** [comment]
It looks like `Model.all` returns a scoped active model relation in 4.2.2. Does your experience differ?

If that's the case `.all` can be a drop in replacement, I think.
