### ISSUE TITLE
Optional zipcode field when registering bicycle

### ISSUE THREAD

**Issue by AWildColin** [bikeindex/bike_index#111]
In an effort to get some sort of measurable data on how many people are registering their bicycle(s) in a specific geographical location, I want to propose the following suggestion:

An optional "zipcode" field when registering/editing a bicycle.

While this currently goes against BI's policy of not collecting any data that could link a bike to it's location for security, let me offer the following argument.

- Because it's optional, users have the choice of whether or not to provide it
- If approved, it would not be displayed on the information page for registered bicycles
- The only function this would serve is a set of new API calls that would allow people to query how many bicycles have been registered in a specific zipcode or range of zipcodes
- If we wanted to get really fancy, we could set up these new API calls so we can query specific locations (e.g. "Rochester, NY") and the API automatically looks up and returns data on the applicable zipcodes.

The only real con of implementing this is:

- If the Bike Index database is ever compromised, a malicious actor could narrow down a potentially expensive and unique bicycle to its zipcode. While this is a relatively limited concern, it's still worth mentioning. I think it is something we can warn users with a little question mark (?) symbol that displays a tooltip of why we would like this data and the potential risk associated with providing it. 

Visually, I know how I would want this to display, but it might take me some time to figure out how to bang out the code, especially the API changes. I want to get a green light before I start working on this.

I'm singlehandledly trying to promote BI in the DC/DMV area and this suggestion would help me get an idea of how many people are registering their bikes.

**Comment by sethherr** [comment]
We actually already have a location field for zipcode, but since we don't prioritize it, it doesn't get filled in too many times.

You could add that to the fields on the API for PUT and POST requests if you'd like.

![screen shot 2016-01-07 at 11 04 34 am](https://cloud.githubusercontent.com/assets/1235441/12176750/8f57f06c-b52e-11e5-9a59-05d15beb1b1f.png)

**Comment by sethherr** [comment]
You could also add the fields required for geolocation on bikes, and then add the code for adding a separate count endpoint for non-stolen bikes - similar to https://bikeindex.org/documentation/api_v2#!/bikes_search/GET_version_bikes_search_count_format_get_3

**Comment by AWildColin** [comment]
Huh. I could've sworn that the last time I added a bike, that field wasn't there. Anyways, yeah, that's everything. Thanks.
