### ISSUE TITLE
Consider adding minimal validation of email addresses

### ISSUE THREAD

**Issue by jmromer** [bikeindex/bike_index#1144]
When we attempt to send an email to a malformed destination email address, we get the following:
https://app.honeybadger.io/projects/35931/faults?sort=last_seen_desc&q=RCPT+TO+syntax+error+

Sometimes this occurs to what appears to be user error (e.g., "name.gmail.com" or "namegmail.com" instead of "name@gmail.com"). 

We may want to consider adding some minimal client-facing validation for emails.

**Comment by sethherr** [comment]
We do have some minimal client side validation of emails - but only on account signup, I believe. It probably makes sense to do other places

**Comment by jmromer** [comment]
We might have some lingering bad data in that case. Testing signup now, I'm not seeing any user-facing validation errors (although the signup process is halted)

```rb
User.where("email NOT LIKE '%@%'").pluck(:email).sample(5)
# => ["cowles", "greenup", "elizabethshiao.gmail.com", "0715440600", "\"><img src=\"x\" onerror=\"alert(1)\"/>"]

User.where("email NOT LIKE '%@%'").count
# => 162
```

![demo](https://user-images.githubusercontent.com/4433943/62549383-67291080-b836-11e9-88ee-09c856c7dd5e.gif)

**Comment by sethherr** [comment]
Ahhh. We have [mailcheck](https://github.com/mailcheck/mailcheck) - which corrects common misspellings. And is also unmaintained (and is also made by @derrickko, heyo buddy!). So we get this:

<img width="959" alt="Screen Shot 2019-08-06 at 10 00 21 AM" src="https://user-images.githubusercontent.com/1235441/62551658-04357a80-b832-11e9-983b-92656b714b9a.png">

Which is evidently not enough. Related to #325 and #134
