### ISSUE TITLE
Re-add strava authentication

### ISSUE THREAD

**Issue by sethherr** [bikeindex/bike_index#1255]
Strava authentication is broken.

It looks like the gems are unmaintained [gem in Bike Index now](https://github.com/thogg4/omniauth-strava), [maybe official gem](https://github.com/tildedash/omniauth-strava-oauth2).

Because this is causing problems for our users, I hid the auth button in #1254

At some point we may want to re-add it (or we can close this PR if it no longer seems relevant)

**Comment by sethherr** [comment]
No longer a priority

**Comment by realchrisolin** [comment]
Any chance you could query the prod DB to see how many users had Strava OAuth set up? I was using it to login and I doubt I'm the only one. While I'm smart enough to know to request a password reset email to get back into my account, I feel like this going to inadvertently lock users out of their accounts temporarily. I figure most people are going to try logging in to report a stolen bike and the experience of not being able to (seemingly) log back in to their account will be understandably frustrating.
