### ISSUE TITLE
Improve twitter error handling

### ISSUE THREAD

**Issue by sethherr** [bikeindex/bike_index#1261]
#1260 made our twitter accounts record errors, which is a big win! There are additional things that would improve this process

Just to write down the easy future wins:

- Show the actual error on the account show page
- Prevent approving a stolen bike that will be tweeted by a twitter account with an error
  - which means we'll need a button to clear the error manually. And we might want to remove the automatic clearing of the error when tweeting.

**Comment by sethherr** [comment]
Has this been resolved @jmromer ?

**Comment by jmromer** [comment]
Yup! Closing
