### ISSUE TITLE
Handle incorrect emails

### ISSUE THREAD

**Issue by sethherr** [bikeindex/bike_index#130]
SparkPost sends us errors when it can't send because of invalid emails.

`Net::SMTPSyntaxError: 501 5.5.2 RCPT TO syntax error`

We should probably delete the user account if this happens. We definitely shouldn't retry the `email_confirmation_worker` 18 times, which is what we do right now :joy_cat:

**Comment by mftaff** [comment]
@sethherr is this still an issue? I am new-ish to open source contributions, and would love to give it a shot?

**Comment by sethherr** [comment]
This is still an issue @mftaff - it would be lovely if you gave it a shot.

**Comment by parker-erickson** [comment]
Hey! I see this issue is pretty old, I am also new to open source contributions, and if this is still needed I would love to try solving the problem. Could I give it a go?

**Comment by sethherr** [comment]
Hey @parker-erickson  - thanks for your enthusiasm! Looking at the current errors, it doesn't seem like the sparkpost issue is still a problem.

Thanks for saying something, this seems like it can be closed.

Look for another issue that seems interesting and comment over there?
