### ISSUE TITLE
Fix issues with partner sign in

### ISSUE THREAD

**Issue by sethherr** [bikeindex/bike_index#1302]
When you sign in or sign up with a partner parameter, for example: https://bikeindex.org/session/new?partner=bikehub

You should be immediately redirected after sign in to `https://new.bikehub.com/account` - from the `sign_in_and_redirect(user)` method in `Sessionable`.

Currently, you are not redirected.

**Comment by sethherr** [comment]
Additionally - if you are signing up via a partner, we need to _require_ that you agree to the terms, rather than just letting you accept them when you next sign in.

**Comment by sethherr** [comment]
This _might_ be an issue with something in the sign in process. When clicking the sign up link on [new.bikehub.com](https://new.bikehub.com), if I'm not already signed in to Bike Index, it doesn't send me to a sign in page with `?partner=bikehub`

**Comment by jmromer** [comment]
Intermittent:

![demo](https://user-images.githubusercontent.com/4433943/66869763-0886be00-ef6e-11e9-89f5-306163599691.gif)
