### ISSUE TITLE
Exclude Project529 Bikes already present in our db?

### ISSUE THREAD

**Issue by jmromer** [bikeindex/bike_index#1343]
The 529 Garage API might be responding with records sourced from Bike Index (provenance isn't indicated in responses) — we may want to check for a serial number exact match before persisting to `external_registry_bikes`:

<img width="1119" alt="Screen Shot 2019-10-16 at 9 45 08 AM" src="https://user-images.githubusercontent.com/4433943/66925104-d622a280-eff9-11e9-955d-8debba99c901.png">

https://bikeindex.org/bikes?serial=T04069299&button=&location=you&distance=100&stolenness=all

**Comment by sethherr** [comment]
It looks like that bike was just double listed. I think we can ignore this issue for now. Closing until it becomes a bigger problem
