### ISSUE TITLE
Question Marks Overlap Password Plugin Icon

### ISSUE THREAD

**Issue by moleon** [bikeindex/bike_index#155]
https://bikeindex.org/bikes/new

<img width="1187" alt="screenshot 2016-04-14 12 46 53" src="https://cloud.githubusercontent.com/assets/2424983/14537952/fe49e374-023e-11e6-8089-e6332617762a.png">

**Comment by sethherr** [comment]
@moleon - where should I put the question mark?

**Comment by sethherr** [comment]
Won't fix
