### ISSUE TITLE
CORs issue with https://bikeindex.org:443/api/v3/search

### ISSUE THREAD

**Issue by catdoch** [bikeindex/bike_index#1573]
When attempting to fetch data with `https://bikeindex.org:443/api/v3/search` I receive a CORs error like this `Access to fetch at 'https://bikeindex.org/api/v3/search' from origin 'https://www.mobile.gumtree.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Is there a workaround to this?

**Comment by sethherr** [comment]
Working on it! Thanks for the heads up @catdoch. 

I'll comment here again when the fix has been deployed. Sorry about that!

**Comment by sethherr** [comment]
Hey @catdoch - the cors header fix is live. Let us know if you run into other problems, thanks for letting us know about this one 🙂

---

Also, you don't need to include the port in the url - you can just use `https://bikeindex.org/api/v3/search`

**Comment by catdoch** [comment]
Cheers for the quick turnaround, works perfectly now 🙂
