### ISSUE TITLE
Remove all references to slavery

### ISSUE THREAD

**Issue by thoran** [bikeindex/bike_index#1644]
Consistent with https://tools.ietf.org/id/draft-knodel-terminology-00.html#rfc.section.1.1.1 and with #1639 all references to slavery should be changed to a nicer term.

**Comment by sethherr** [comment]
Do you have specific things that you're pointing to for removal?

I see a few instances of `black.?list` and `white.?list` to rename, but if there are other things, it would be great to surface them here

**Comment by sethherr** [comment]
In the absence of additional suggestions, I'm going to close this with #1645, which addresses blacklist and whitelist.

If there are pieces of oppressive language, please either reopen this or open a new issue!
