### ISSUE TITLE
Password reset not working

### ISSUE THREAD

**Issue by fernandesnikhil** [bikeindex/bike_index#1688]
I believe there are 2 problems with the password reset mechanism.
1) Email with reset instructions are not always dispatched
2) After following a link to reset the password - the reset always fails. See screenshot below for error message.

[https://ibb.co/WPmM1xz](https://ibb.co/WPmM1xz)

What I did:
Select forgot password on the login page. Entered my registered email address. Waited 15 minutes for an email. No email appeared in Spam/Inbox. Clicked "forgot password" again, entered my registered email address. Got an email in the Inbox almost immediately. Clicked on the Reset link in the email. Filled in a new password, clicked continue - got the error message "We're sorry, but that link is no longer valid." Thinking that the backend might have sent out a new link because I did hit reset twice I waited. Nothing showed up in my email. Clicked on Reset again, entered my registered email, got an email in my inbox near instantly. Followed the Reset link, filled in a new password, clickec continue and received the same error message - "We're sorry, but that link is no longer valid." Clicked on the Reset button again - no email received. Hence I think there are two distinct bugs I encountered.

**Comment by fernandesnikhil** [comment]
UPDATE: looks that the reset to a new password went through even though the error suggests it didn't.

**Comment by sethherr** [comment]
Hey @fernandesnikhil - did you by chance use a yahoo.com email?

Regardless, please check your spam folder and mark us as _not spam_ if we're in there. This is the reason we're having issues with deliverability - particularly to Yahoo.

Based on your experience, it seems like I should just make the expiration a little slower, to account for some deliverability issues.

**Comment by sethherr** [comment]
I have addressed this issue, and so I'm closing it. Please let me know if you run into the problem again!

**Comment by fernandesnikhil** [comment]
@sethherr sorry for the late rely. The email provider was Gmail.
I didn't find any emails in the Spam folder.

Thanks for the update.

**Comment by sethherr** [comment]
OK! Good to know, thanks for following up @fernandesnikhil
