### ISSUE TITLE
Revised layout for admin pages

### ISSUE THREAD

**Issue by sethherr** [bikeindex/bike_index#175]
~Lowest priority. Shouldn't be done till absolutely everything else is~

**Comment by sethherr** [comment]
At this point, this is something we want to do. The steps I think should be followed to take care of this:

1. Create a new partial layout with the admin header in it
2. Render that partial below the standard header in the revised layout and make the normal header not fixed if in the admin section (I think both should just stay at the top of the screen in admin)
3. Switch admin controllers gradually over to use the new layout, keeping things looking roughly similar to the way they look in admin right now.

Looking at the uncompiled, unminified scss files for admin might be useful. I figured out the commit where they were removed in #465 -

> The original style compilation files (pre removing updated_styles) are visible Style compilation files removal are visible in this commit: 1a8ebdf - PR #224

**Comment by Robertgervais** [comment]
- [ ] SOMETHING blah blah

**Comment by Robertgervais** [comment]
- [x] Ads
- [x] Ambassador Tasks Assignments
- [x] Ambassador Tasks
- [x] Bike Codes
- [x] Bikes
- [x] Bulk Imports
- [x] Ctypes
- [x] Dashboard
- [x] Exports
- [x] Failed bikes
- [x] Feedbacks
- [x] Graphs
- [] Mail Snippets
- [x] Manufacturers
- [x] Memberships
- [] News
- [x] Organization Invitations
- [] Organizations (Almost, just needs custom layouts done)
- [] Ownerships
- [x] Paid Features
- [x] Paints
- [x] Partial Bikes
- [] Payments
- [x] Recoveries
- [x] Recovery Displays
- [x] Stolen Bikes
- [x] Stolen Notifications
- [x] Tweets
- [x] Users

**Comment by Robertgervais** [comment]
Hooooo yeah, this is DONE. I can either close this, or tomorrow I can go through and reference all the PR's that are involved in this.
