### ISSUE TITLE
Reporting found bike

### ISSUE THREAD

**Issue by Jack11111** [bikeindex/bike_index#1836]
Not sure this is the right channel for this... Im trying to figure out how to contact the owner of a stolen bike from an iOS app (in case of found). I don't see anything related to retrieving a bike owner's contact info on the API (https://bikeindex.org/documentation/api_v3). Also, how do I register/login a user? The api only seems to cover retrieving info about "current user" which doesn't help since you can't access account info via the API. Am I missing something??? 

Appreciate your help on this!

**Comment by sethherr** [comment]
First - there is a way to send messages through the API through `POST /v3/bikes/{id}/send_stolen_notification`

But your application has to be approved to be able to use that functionality. Send an email to `seth@bikeindex` and let me know what you're planning on doing with your application.

For signing a user in - you have to use OAuth2. Here is [a good general tutorial about OAuth2](https://oauth.net/2/) - some of which might not be applicable, but hopefully that will point you in the right direction.

I'm going to close this issue, send me an email if you have any more specific questions about how things work!
