### ISSUE TITLE
Top of search page edits

### ISSUE THREAD

**Issue by moleon** [bikeindex/bike_index#191]
- [x] don't say the IP number. just say "you"
- [x] tabs should be 12px, not 15. Also, they should never extend into two rows.
- [x] 'current' tab should have bold text
- [x] ~~all bike pics should be the same aspect ratio as the thumbnails. No more squares.~~
- [ ] **Mike's UX wishlist. ** Can the thumbnail expand to a bigger pic of the bike on hover? I think this would be good and is important for people who don't want to have to click deeper.
- [x] There is a weird extra space following the brand name of the bike
- [x] The little geo-location input fields are gone when a search has been executed.

![top-of-search-page-edits-bike-index](https://cloud.githubusercontent.com/assets/2424983/14960654/52529e32-105b-11e6-829e-7492d0c6f3a8.jpg)

**Comment by AWildColin** [comment]
Instead of replacing the IP address with "you", perhaps we should replace it with the value of what is being searched (e.g. city name, zip code, etc)?

**Comment by sethherr** [comment]
@AWildColin & @moleon re: the IP issue, it's already in an issue - #190 - I'll be storing it and referencing that stored thing

**Comment by sethherr** [comment]
@moleon - make a fast (e.g. just photoshop a screenshot) mockup of the bigger thumbnail

**Comment by sethherr** [comment]
> The little geo-location input fields are gone when a search has been executed.

They only show up on the proximity search page. Does that seem unreasonable?

**Comment by moleon** [comment]
It should be on both- because what if someone wants to widen their area after they don't get any hits?

**Comment by sethherr** [comment]
I'm closing this with the PR request. @moleon if you put up a wireframe with an expanding on hover image, reopen this.

**Comment by moleon** [comment]
Here's a screenshot-

- [ ] Also,regarding the IP number, I think the problem is that an IP isn't humanspeak. Even if you're using their IP, just say "within 100 miles of your IP" The value of the number is meaningless.

- [ ] Also also, why is the default search the middle tab? You should either re-order the tabs. Or (better option) make the default search within 100 miles of the IP.

![screenshot 2016-05-03 15 13 11](https://cloud.githubusercontent.com/assets/2424983/14996834/93f3ab38-1141-11e6-94f9-3e457ac43a28.png)

**Comment by sethherr** [comment]
BECAUSE THE IP ISSUE IS COVERED IN #190.
