### ISSUE TITLE
Top of Bike Show Notes

### ISSUE THREAD

**Issue by moleon** [bikeindex/bike_index#192]
- [x] Too much space between title and "last seen at" Get rid of h1's bottom margins
- [x] gosh. does "contact the owner now not have enough room? That line shouldn't break. maybe the font needs to be smaller.
- [x] pre-input text should be italic
- [x] can we add some logic to the persons phone number? some nice little dashes? 4656676453 looks like a serial number
- [x] There should be 48px between the tall ad and the contact box
- [x] when the user hovers over the bike, there should be a magnifying glass, not a hand
- [x] ~~the facebook sharing buttons should look like the twitter buttons but with facebook colors~~
- [x] It's looking great.

![bike-show-notes](https://cloud.githubusercontent.com/assets/2424983/14961935/f8293b80-1061-11e6-805f-5a84c0c21a00.jpg)

**Comment by sethherr** [comment]
The facebook and twitter buttons are provided by facebook and twitter, not something we're implementing ourselves. And we aren't using a malware service like (ShareThis)[http://www.sharethis.com/]

**Comment by sethherr** [comment]
Added periods, they're more international

**Comment by sethherr** [comment]
> does "contact the owner now not have enough room? That line shouldn't break. maybe the font needs to be smaller.

I like the mobile styles, where the contact is hidden behind a button, when shown it's larger.
