### ISSUE TITLE
Revised layout for users personal pages

### ISSUE THREAD

**Issue by sethherr** [bikeindex/bike_index#206]
e.g. [/users/seth](https://bikeindex.org/users/seth)

**Comment by sethherr** [comment]
Highlighted on the forums - https://discuss.bikeindex.org/t/beautify-public-facing-user-page/254

**Comment by sethherr** [comment]
![user-profile-page-draft](https://cloud.githubusercontent.com/assets/1235441/16691254/8b846e4a-44f1-11e6-858e-e98d6f00aaf9.jpg)
![user-profile-page-mobile-draft](https://cloud.githubusercontent.com/assets/1235441/16691255/8b85aa08-44f1-11e6-9d44-bff294406fa7.jpg)

**Comment by timlkelly** [comment]
closed #235
