### ISSUE TITLE
Replace all the gutter padding in revised stylesheets with variable

### ISSUE THREAD

**Issue by sethherr** [bikeindex/bike_index#208]
instead of `0.9375rem` use the bootstrap 4 variable, whatever it is.

**Comment by Chris-Wong-1** [comment]
@sethherr Hello! I'm new and looking for small ways I can help. I was just looking into this and from what I've read it seems like `rem` is the preferred variable in bootstrap 4. Sources: [getbootstrap.com](http://v4-alpha.getbootstrap.com/migration/#global-changes)
[scotch.io](https://scotch.io/bar-talk/whats-new-in-bootstrap-4#improved-grid-system-based-on-rems)
Please let me know if I'm wrong or confused. If you point me to the stylesheet you were thinking about I'd be happy to look into it more.
Thanks!
Chris

**Comment by sethherr** [comment]
Hey @Chris-Wong-1 - we'd love to have your help!

`rem` *is* what bootstrap uses to define widths - but they define a `$gutter` variable, probably in `rem` [it's at least used in the grid mixin](https://github.com/twbs/bootstrap-rubygem/blob/master/assets/stylesheets/bootstrap/mixins/_grid.scss). I'm not positive it's equal to `0.9375rem` - but it probably is, and if so, that's the variable to replace all instances of `0.9275rem` in the scss.

Also, even if there is no matching bootstrap variable, it would be great to create our own and remove repeated explicit numbers from the scss - to make reading the scss clearer, prevent possible typos, and make maintenance easier.

**Comment by sethherr** [comment]
No longer relevant
