### ISSUE TITLE
Add Location for orgs doesn't seem to be working at all

### ISSUE THREAD

**Issue by moleon** [bikeindex/bike_index#213]
I need to get at it so I can see how that functionality works. Also, users might like it. it's in /organizations/org_name/edit#

![screenshot 2016-05-11 13 42 53](https://cloud.githubusercontent.com/assets/2424983/15192378/84467cf4-177e-11e6-8fec-6904e9c55b47.png)

**Comment by sethherr** [comment]
Fixed
