### ISSUE TITLE
Seed task broken - Missing manufacturers

### ISSUE THREAD

**Issue by barefootford** [bikeindex/bike_index#2176]
Hey @sethherr I'm getting an issue while running the seed task, specifically `seed_test_users_and_bikes`.

```andrew@andrews-m1-MacBook-Air bike_index % rake seed_test_users_and_bikes
Users added successfully
rake aborted!
NoMethodError: undefined method `name' for nil:NilClass
/Users/andrew/code/bike_index/lib/tasks/seed_tasks.rake:60:in `block (2 levels) in <main>'
/Users/andrew/code/bike_index/lib/tasks/seed_tasks.rake:39:in `times'
/Users/andrew/code/bike_index/lib/tasks/seed_tasks.rake:39:in `block in <main>'
Tasks: TOP => seed_test_users_and_bikes
(See full trace by running task with --trace)
andrew@andrews-m1-MacBook-Air bike_index % rake seed_test_users_and_bikes
Users added successfully
```

I think I've traced the bug down to this chunk of code.
https://github.com/bikeindex/bike_index/blob/aebbc020ba7ec4f3e6814f47fb2f40c1c2e2ff20/lib/tasks/seed_tasks.rake#L53-L55

`bike.manufacturer.name` manufacturer is nil so nil on nil is a no-go.

https://github.com/bikeindex/bike_index/blob/aebbc020ba7ec4f3e6814f47fb2f40c1c2e2ff20/lib/tasks/seed_tasks.rake#L37

It looks like `bike.manufacturer` is nil since earlier when we assign random manufacturers ids there aren't any Manufacturers present.

```
From: /Users/andrew/code/bike_index/lib/tasks/seed_tasks.rake:41 :
    40:     binding.pry
 => 41:     bike = Bike.new(
    42:       cycle_type: :bike,
    43:       propulsion_type: "foot-pedal",
    44:       manufacturer_id: (rand(Manufacturer.frame_makers.count) - 1),
    45:       rear_tire_narrow: true,
    46:       handlebar_type: HandlebarType.slugs.first,

[1] pry(main)> Manufacturer.count
=> 0
```

Happy to fix this with a new rake task, `seed_test_manufacturers` or can just add a few lines to add manufacturers before saving bikes.

Existing stuff:

https://github.com/bikeindex/bike_index/blob/aebbc020ba7ec4f3e6814f47fb2f40c1c2e2ff20/lib/tasks/seed_tasks.rake#L6-L18

new stuff??

```ruby
manufacturer_attrs = {
    soma: {name: "Soma Fabrications", slug: "soma" },
    riv: {name: "Rivendell Bicycle Works", slug: "riv" },
    specialized: {name: "Specialized Bicycles", slug: "specialized" },
}

manufacturers = manufacturer_attrs.values.map {|attributes| Manufacturer.create(attributes)}
manufacturer_ids = manufacturers.map(&:id)

...
manufacturer_id: (manufacturer_ids.sample),
...
```

**Comment by sethherr** [comment]
Sorry about this @barefootford !

Working on fixing it now.

**Comment by sethherr** [comment]
Should be fixed! Please let me know if it isn't.
