### ISSUE TITLE
User settings page revisions

### ISSUE THREAD

**Issue by moleon** [bikeindex/bike_index#218]
All issues are in the image. The "update password" section is particularly confusing as there are three different password fields. What is the need for "password" and "current password" ? Is one of those supposed to say new password?

My suggestion is to title that particular form "Change Password" and the field titles should be, in order: New Password, Confirm New Password, and Old Password

Also, too many buttons and too much green. 

![screenshot-2016-06-03-13 42 22](https://cloud.githubusercontent.com/assets/2424983/15789693/32133af4-2993-11e6-997b-564fce1df9da.png)

**Comment by timlkelly** [comment]
We need multiple pages to make this not a mess! Pages:

- Account information
- Password
- Sharing and personal page

**Comment by sethherr** [comment]
Before merging this in, we need to fix #226
