### ISSUE TITLE
NFT of Bike Registration

### ISSUE THREAD

**Issue by jakebruemmer** [bikeindex/bike_index#2193]
Hear me out - not trying to troll here.

I've recently started using Bike Index and really like the site. I've thought that a tool like this is necessary for bikes as there's effectively no gov't registration system for them. I also think that a registration system will become more important over time if the e-bike segment of the bike market continues to grow (which I think it will). 

# Idea

[Non Fungible Tokens](https://en.wikipedia.org/wiki/Non-fungible_token) are data stores on a blockchain that can be used to verify authenticity of ownership. They can be transferred from one owner to another, but the current owner of the NFT is the verified owner of the it. 

By associating an NFT to each bike on your account, you could certify that you're true owner of the bike. This would add a layer of security in the registration system on top of what exists. 

The QR codes that you can get for your bike do already offer some of this functionality. However, the QR code could be duplicated or removed from the bike by a thief. 

As far as the implementation, the idea would be to:
* Optionally allow for users to have an NFT for each of their bikes
* Support transfers of NFTs through Bike Index to new owners (if desired by the new owner)

What the implementation should not be:
* Creating a marketplace for flipping/speculating on bike NFTs
* Force users to buy things (the NFT) if they don't want it
* Make Bike Index into a crypto project

----

Curious to hear what others think.

**Comment by sethherr** [comment]
A central reason I care about bikes (and believe stopping bike theft is important) is because of an environmental ethic. 

How do you propose participating in crypto in an environmentally friendly way?
