### ISSUE TITLE
Org Admin Page Feedback pt. 1

### ISSUE THREAD

**Issue by moleon** [bikeindex/bike_index#220]
All of my comments are in the images. More to come. I have to boogie for the day.

1. [x] Align left
![screenshot 2016-06-22 15 29 27](https://cloud.githubusercontent.com/assets/2424983/16282560/e39542e0-388e-11e6-948a-019ba2ab68e0.png)

2. [x] File upload button
![screenshot 2016-06-22 15 20 55](https://cloud.githubusercontent.com/assets/2424983/16282559/e3946b9a-388e-11e6-91ea-2081c4b83de8.png)

3. [x] Invite user, user menu
![screenshot 2016-06-22 15 11 29](https://cloud.githubusercontent.com/assets/2424983/16282558/e393e918-388e-11e6-8ce6-d873b63e0d2e.png)

4. [x] Menu collapse
![screenshot 2016-06-22 14 54 12](https://cloud.githubusercontent.com/assets/2424983/16282561/e39b7d4a-388e-11e6-87b9-6317339d640a.png)

**Comment by sethherr** [comment]
1. Cool. Will fix
2. File upload button in bootstrap 4 doesn't show filename on upload. I think this might be causing confusion elsewhere, so I'll figure out a fix
3. I'd like to discuss the menu with you. Whenever you're free
4. Re: too tall, fixing. Menu collapse, see above.
