### ISSUE TITLE
Redirecting to logout loop

### ISSUE THREAD

**Issue by sethherr** [bikeindex/bike_index#227]
Somehow, I managed to get a session/cookie setup that immediately redirected me to logout after logging in, and I couldn't resolve it other than by removing the cookie.

Not good.

**Comment by sethherr** [comment]
Ran into the issue again. Unclear what caused it, once again. Removed the `_bikeindex_session` cookie in Chrome, and when I logged in again it actually displayed the `handle_unverified_request` alert (previously it had silently failed).

When I attempted to log in again, it worked.

**Comment by alexckime** [comment]
I'm not sure why I receive these emails. I've marked "ignore" in github,
but it didn't stop these.

Are these going to a specific person who is forwarding me their mail? What
is happening?

Not sure if anyone will actually read this, but if this was fixed it would
be cool.

Seth Herr
Bike Index co-founder
BikeIndex.org <https://www.bikeindex.org/>
Facebook <https://www.facebook.com/bikeindex>
