### ISSUE TITLE
Status and stolen from API not consistent with webpage

### ISSUE THREAD

**Issue by hanochyeung** [bikeindex/bike_index#2326]
Have been consuming the api for the app and I've been running into cases where the bike is marked stolen on the website but through v3 API stolen is false and status is with owner

**Comment by hanochyeung** [comment]
Seems like issue lies with stolen record not being created. @sethherr do you have any ideas?

**Comment by sethherr** [comment]
Can you post an example you've found @hanochyeung ? or email me, seth@bikeindex

**Comment by hanochyeung** [comment]
@sethherr yes, I'm reproducing this with bike id 1184882 . When fetched via the api doesn't have stolen information set but on website it's clearly marked

**Comment by sethherr** [comment]
For me it _does_ have the stolen record and information.

Is there any way that caching is happening on your side?

**Comment by hanochyeung** [comment]
Hello,

No, I've been able to reproduce this repeatedly even by clearing all
storage and reinstalling my app. For the fetching I haven't added any
caching.

Okay, I guess really I'm just wondering why the stolen data isn't being
surfaced when it's queried in the api.

You can do just a normal search with query Brompton

Thanks

**Comment by sethherr** [comment]
Sorry for the delayed resolution to this, it took me a little while to track down!

This is deploying now, it should be fixed in 30 minutes. @hanochyeung, if you're willing to test it and report back that would be amazing!

**Comment by hanochyeung** [comment]
Hey Seth!

Seems to work from initial impressions but I'll do some further testing :)

With this I will try to get the initial version launched this weekend to
play store! Let me know if there's anyone I can connect with on the bike
index side if there's specific requirements or feature requests.

Thanks so much
Hanoch Yeung
