### ISSUE TITLE
Add excel export functionality for organization bikes

### ISSUE THREAD

**Issue by sethherr** [bikeindex/bike_index#264]

**Comment by sethherr** [comment]
Shhhhhhhh

**Comment by stevepiercy** [comment]
I would like this feature for GEARs.

Right now I can't really do much reporting to measure the efficacy of providing bike security education to people. For example out of all the bikes registered through GEARs, how many were reported stolen? Compare that to the general population within a 30-mile radius.

**Comment by sethherr** [comment]
We actually have this functionality! It's a paid feature for organizations @stevepiercy. We'll follow up via email
