### ISSUE TITLE
Dropdown UI problems in register new bike and edit bike

### ISSUE THREAD

**Issue by wonderificdave** [bikeindex/bike_index#268]
When I go to add a new bike, the dropdowns like bike type and color are really strange like they are missing images or sizing.  It is very difficult to use in the current state.

Tested using  Chrome - Windows 10, Firefox Windows 10, Chrome - Android with same behavior in all

![image](https://cloud.githubusercontent.com/assets/778066/18535612/83c4f1fe-7aaa-11e6-9cbe-f39b13a4d141.png)

**Comment by sethherr** [comment]
@wonderificdave thanks for the heads up!

**Comment by wonderificdave** [comment]
No problem!  Keep up the great work!
