### ISSUE TITLE
Confirmation email doesn't have confirmation link

### ISSUE THREAD

**Issue by moleon** [bikeindex/bike_index#290]
![screenshot 2016-09-29 14 36 59](https://cloud.githubusercontent.com/assets/2424983/18969304/47f898f2-8652-11e6-8329-9d37956931dd.png)

**Comment by sethherr** [comment]
Only because you've already claimed this bike.

If you haven't claimed it, it will prompt you to claim it

![screen shot 2016-10-14 at 5 36 13 pm](https://cloud.githubusercontent.com/assets/1235441/19404575/c373e318-9234-11e6-9a32-b0020770a5c5.png)
