### ISSUE TITLE
Search proximity broken

### ISSUE THREAD

**Issue by realchrisolin** [bikeindex/bike_index#303]
Users can no longer search for stolen bicycles "within X miles of you". Example link: https://bikeindex.org/bikes?utf8=%E2%9C%93&query=&button=&proximity=20001&proximity_radius=10&stolen=true&non_stolen=&non_proximity=#

Observe how all bicycles are shown instead of those within a 10 mile radius of zipcode 20001.

**Comment by sethherr** [comment]
Well... that isn't the URL you should be using, the parameters changed. If you input things on the site you would get the correct search: https://bikeindex.org/bikes?location=20001&distance=10&stolenness=proximity

For future reference - the HTML portion of the site and parameters used will be updated (infrequently) without notice. It's intended to be accessed by humans, not programmatically.

The API version (V2) that was current when you created that link will still respond correctly https://bikeindex.org/api/v2/bikes_search?utf8=%E2%9C%93&query=&button=&proximity=20001&proximity_radius=10&stolen=true&non_stolen=&non_proximity=# - but it is deprecated and it would be a good idea to switch to [the current version](https://bikeindex.org/documentation) that uses the new parameters.

**Comment by realchrisolin** [comment]
That's makes sense, but the actual search function wasn't working either. Between that and not knowing the parameters had changed, all I could do is open an issue with the last known working URL. A love note in the commit messages would be nice, if possible. 👍
