### ISSUE TITLE
Warning for email address with correct TLD - top level domain name

### ISSUE THREAD

**Issue by wonderificdave** [bikeindex/bike_index#325]
Trying to transfer ownership to someone with a xxx@yyy.tv email address.  Getting a yellow warning saying: "Did you mean xxx@yyy.ca?".  Looks like the save may have happened correctly, but not sure if the email was sent out or any other errors occurring.

Expected behavior - no warning shown, new owner gets the email

List of valid top level domains:
https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains

**Comment by sethherr** [comment]
@wonderificdave we use [mailcheck](https://github.com/mailcheck/mailcheck) to offer suggestions if it seems like the email address could be a typo. We allow you to send to any domain though - so your message went through.

While there will be a few people who see the message who it doesn't apply to, the number of invalid emails we deal with has been dramatically reduced.

Thanks for noticing, and I'm sorry it made you concerned that you may not have transferred ownership.
