### ISSUE TITLE
CSV export for schools

### ISSUE THREAD

**Issue by runt2pb** [bikeindex/bike_index#369]
Create a feature that will export data from a Bike Index organization so that schools can generate reports and import bikes into other systems, such as T2, if they wish. Perhaps this is a button schools can click that will download a CSV file of the data onto their computer. 

This should only be a feature for paid organizations - in fact, this could plausibly be a feature that costs a little bit extra ~$150-$200. This feature replaces about 4 hours of manual work for Lily when a school requests some sort of report.

**Comment by sethherr** [comment]
resolved by #446
