### ISSUE TITLE
Mailchimp newsletter

### ISSUE THREAD

**Issue by runt2pb** [bikeindex/bike_index#370]
Create a mailchimp of all Bike Index users who have checked the box upon registration to receive Bike Index newsletters, as well as emails of those who responded positively to terms update (excel file sent via email for privacy policy reasons).

Show Lily how to use this list to send monthly newsletters.

**Comment by realchrisolin** [comment]
Probably not a huge deal since very few people are watching this project and I don't think file attachments in github issues are spidered, but are we violating the private policy by making this email list public for anyone on the internet to see?

**Comment by runt2pb** [comment]
Oh shit!!! you're right

Lily Williams
Communications Director
BikeIndex.org
https://bikeindex.org/support_the_index

**Comment by sethherr** [comment]
Resolved by #383
