### ISSUE TITLE
Error 522

### ISSUE THREAD

**Issue by runt2pb** [bikeindex/bike_index#374]
This is appearing for www.bikeindex.org/upitt

![unnamed](https://user-images.githubusercontent.com/29760224/35891186-047f8a36-0b71-11e8-83b5-9fd9dad571f2.jpg)

**Comment by realchrisolin** [comment]
It's back up and seemingly loading without noticeable issues. My developer account doesn't give me access to any server logs, so this will need @sethherr at the minimum to investigate what died.

![image](https://user-images.githubusercontent.com/1288116/35895478-9abf7254-0b85-11e8-8b76-c6bb0cd283e1.png)

**Comment by runt2pb** [comment]
Not working on my end. Perhaps a browser issue?

Lily Williams
Communications Director
BikeIndex.org
https://bikeindex.org/support_the_index

**Comment by realchrisolin** [comment]
It's down for me now too. Looking up the relevant code, this seems like a server side issue:

`config/routes.rb`
```
  resources :organizations do
    member do
      get :embed
      get :embed_extended
      get :embed_create_success
    end
  end

  get '/', to: redirect(:root_url, subdomain: false), constraints: { subdomain: 'stolen' }
  root to: 'welcome#index'

  LandingPages::ORGANIZATIONS.each do |slug|
    get slug, to: 'landing_pages#show', organization_id: slug
  end

  %w(for_shops for_advocacy for_law_enforcement for_schools new_homepage).freeze.each do |page|
    get page, controller: 'landing_pages', action: page
  end

  %w(update_browser user_home choose_registration goodbye bike_creation_graph).freeze.each do |page|
    get page, controller: 'welcome', action: page
  end
```

If I'm reading the code right, the `/upitt` organization page is calling the `landing_pages` controller, which all of the `for_*` pages are also calling. Strangely, they're all loading (for me) without issue. This really needs Seth to look at as I think he's the only one with access to the Cloud66 account/resources to investigate what's causing this. The `/admin` dashboard doesn't have any error reporting.

**Comment by sethherr** [comment]
This was an issue with our our subdomain redirect. I was only successfully redirecting `http://www.bikeindex.org/...`, not `https://www.bikeindex.org/...` to the correct domain (no www).

This is now fixed!
