### ISSUE TITLE
Encourage people to mark found bikes as found

### ISSUE THREAD

**Issue by runt2pb** [bikeindex/bike_index#395]
Idea:

Automated follow up emails reminding found bike owners to edit their found bikes to reflect such. Simple 1-click "found" links and donate links.

When people don't mark bikes as found, we don't have an accurate number on the site - we technically have recovered more bikes than we say.

**Comment by sethherr** [comment]
#352 added simple 1-click found link

I worry about automated emails to users asking them to mark bikes found, unfortunately, most stolen bikes aren't found and I don't want to make people sad.

Is there a way to phrase stuff such that it sounds good?

**Comment by runt2pb** [comment]
I know Bryan manually sends these emails to anyone who reports a
recovery... But we don't have an automated email that does this, right? I
would also be sad if I received an email when I registered my stolen bike
that told me to mark the bike as found.

I actually think I do remember this. It was something Bryan wanted if I
remember correctly, probably because he is sick of hounding people to mark
their found bikes as found haha.

I would say to not include any of this kind of language in any emails a
person receives for marking their bike as stolen, we could do some sort of
'congratulatory' email when someone marks their bike as 'recovered.' In
this email we could encourage users to mark their bike as found and add any
missing or new info about the bike, e.g.:

*Congratulations! (celebratory graphic/emoji) You recovered your stolen
bike. There are a couple of things you need to do to make sure that your
bike stays in your hands from here on out. *

*First, make sure to mark your bike as 'found' on Bike Index. If it's still
stolen, organizations and individuals will continue to look for it, and
that would be confusing. *

*Next, make sure to add some updated photos and information to Bike Index
about the bike. Chances are, wherever it was, it gained some wear and tear
that might disguise it in case it goes missing again. Make sure people know
what they're looking for. *

*Thanks. The Bike Index Team. *



Lily Williams
Communications Director
BikeIndex.org
https://bikeindex.org/support_the_index

**Comment by sethherr** [comment]
Resolved a bit more, this will always be an issue - but I'm moving on from this for now
