### ISSUE TITLE
Stolen 2007 mongoose Canaan elite medium from Rancho Santa Margarita ca 

### ISSUE THREAD

**Issue by blske101** [bikeindex/bike_index#401]
I’m new to this and I recently had my mtn bike stolen and I’m need to get my serial number to file a police report and the proformance bikes Mission Viejo where it was purchased they said they don’t keep serial number of there bikes and I don’t know what to say about that and I filled mine two moves ago and I just frustrated to no end first time any thing has ever been stolen and I’m not sure ticked off and would love to have my bike to ride and I cannot get any where it seem  could you plead clue me in and point me to get this going and I’m sure not exactly the sharpest tool but I will make up for in persistent and I’m really confused to why they charge 2000 for something they don’t keep track of maybe I am going the wrong way so I’m asku if you can please point me to

**Comment by sethherr** [comment]
Why I’m the world didn’t you list this on Bike Index?

Nobody is going to see this here and it isn’t helpful.

If you want to make it more likely for places like performance to register bikes, donate to us (we’re a non-profit) so we can continue to exert pressure on them and make it happen. 

Regardless - register your bike on bikeindex.org
