### ISSUE TITLE
Attempt to register new bike redirects to an existing bike page

### ISSUE THREAD

**Issue by interstateone** [bikeindex/bike_index#425]
I have two registered bikes. When I try to register a new one I'm taken to one of my existing bikes. I can't find a workaround for this. I've tried logging out, clearing caches and clearing cookies.

A [conversation](https://discuss.bikeindex.org/t/cant-add-more-one-bike/834/2) was started in the forum.

I only know enough Ruby/Rails to be dangerous but [this recently-added line](https://github.com/bikeindex/bike_index/pull/422/files#diff-26ef431de9ae983c68f433b76cc49ce8R92) _sounds_ like what's happening here. It's not clear to me why it's finding a BParam for an existing bike in this case, because I don't see where one of the request params would be set to trigger [that code](https://github.com/bikeindex/bike_index/blame/master/app/controllers/bikes_controller.rb#L217).

**Steps to reproduce:**

Either directly: https://bikeindex.org/bikes/new
Or through navigation:

1. Login
2. In the navigation, upper right, click “Your Bikes”
3. On the right side, click the blue button “Add a Bike”
4. Select one of “Add your own bike”, “Add a stolen bike”, or “Add a stolen/found bike you’ve recovered”
5. Click green button “Register Bike”

**Actual Results:**

I'm redirected to https://bikeindex.org/bikes/33978

![screen shot 2018-08-15 at 6 15 23 pm](https://user-images.githubusercontent.com/594059/44179987-3432bd80-a0b7-11e8-9b69-e262cb19809b.png)

**Expected Results:**

I'm taken to a page where I can enter information to register a new bike

**Comment by stevepiercy** [comment]
There are no request parameters sent with the request. After logging in, then for either method, there is a GET request to `/bikes/new`. In Chrome's Developer Tools > Network > tick "Preserve log" and "disable cache", navigate around, and click on "Doc" to filter the transcript of your activity.

FTR, I go to the Enter Bike Details page.
![google chrome006](https://user-images.githubusercontent.com/102112/44192632-0fedd580-a0e5-11e8-81f4-37c04e954c75.png)

Perhaps try logging out, clearing all cookies from the site bikeindex.org, and try again?

**Comment by sethherr** [comment]
What @stevepiercy recommends is what I would recommend as well - try recording what happens and paste it here (if you'd prefer to not share the output, you could send me it via email - seth at Bike Index's domain)
