### ISSUE TITLE
Add links to IRS site for proof of 501c3 status

### ISSUE THREAD

**Issue by stevepiercy** [bikeindex/bike_index#451]
There are a few pages on the site and blog that reference the 501c3 status of Bike Index.

- [ ] https://bikeindex.org/about
- [ ] https://bikeindex.org/support_bike_index
- [ ] https://bikeindex.org/news/bike-index--now-a-nonprofit

I would suggest that all links that mention the 501c3 status point to https://bikeindex.org/about where content about the status could reside.

Also I would suggest to add a link to the IRS site to establish greater legitimacy, including the EIN of 81-4296194.

https://apps.irs.gov/app/eos/displayAll.do?dispatchMethod=displayAllInfo&Id=5038694&ein=814296194&country=US&deductibility=all&dispatchMethod=searchAll&isDescending=false&city=&ein1=81-4296194&postDateFrom=&exemptTypeCode=al&submitName=Search&sortColumn=orgName&totalResults=1&names=&resultsPerPage=25&indexOfFirstRow=0&postDateTo=&state=All+States

**Comment by sethherr** [comment]
Good suggestion, I will add this

**Comment by sethherr** [comment]
Since we added the EIN to the footer, I don't think it's necessary to link to the IRS?

I'm going to close this - feel free to re-open it if you think it isn't sufficiently solved @stevepiercy

**Comment by stevepiercy** [comment]
Yeah, that's fine. The IRS moved its search tool. If someone wants to dig, they have the EIN.
