### ISSUE TITLE
Validate IRS record

### ISSUE THREAD

**Issue by stevepiercy** [bikeindex/bike_index#452]
https://apps.irs.gov/app/eos/displayAll.do?dispatchMethod=displayAllInfo&Id=5038694&ein=814296194&country=US&deductibility=all&dispatchMethod=searchAll&isDescending=false&city=&ein1=81-4296194&postDateFrom=&exemptTypeCode=al&submitName=Search&sortColumn=orgName&totalResults=1&names=&resultsPerPage=25&indexOfFirstRow=0&postDateTo=&state=All+States

There is a space in the URL for Bike Index, under **Form 990-N (e-Postcard)**:
https://bikeindex.or g

Also suggest updating information as necessary.

**Comment by sethherr** [comment]
Ooh, good catch on the URL. I doubt I included that space when I filed (it's probably some parsing glitch on their part), but I'll make sure I don't when we file next time!

The information otherwise is accurate, as far as I can tell. If there is something you think is incorrect, please email me!
