### ISSUE TITLE
Publish mailing address for receiving paper checks for donations

### ISSUE THREAD

**Issue by stevepiercy** [bikeindex/bike_index#453]
Where do we mail donations? GEARs wants to mail a check for my Ambassador status. I imagine lots of organizations and government agencies still use paper checks and not credit or debit cards.

I could find no mailing address published anywhere on the site. Suggest adding this information to About or wherever there would be a "How to contribute/donate" page.

**Comment by sethherr** [comment]
@stevepiercy I think you've found the answer to this out! Contact us via email and we will figure out where to mail something.

We previously had a published address on the site and it resulted in receiving an enormous amount of unsolicited garbage mail (that still continues, despite unpublishing the address - it is still possible to find an address via business fillings).

Frankly, the time and headache involved with managing that mail stream means it makes much more financial sense to pay payment processing fees than encourage receiving checks.
