### ISSUE TITLE
Dedupped registration API endpoint

### ISSUE THREAD

**Issue by sethherr** [bikeindex/bike_index#517]
Registration through the API for bikes that may have been registered already - only register if the bike hasn't been registered yet.

Potentially add any information that wasn't filled in for the bike already.

This will be useful for recording the serial number of bikes that are being worked on in shops

**Comment by stevenbuccini** [comment]
Pasting @sethherr's notes here for transparency:
> 
> Two ways/places you could add this code:
> 
> In API V3 - create a new API V3 class, copying or inheriting from api v2 bikes
> in the BParam model
> It should be an attribute that you pass when creating a bike (via POST /api/v3/bikes) - documentation is at /documentation. We use Grape for the API, mainly because it auto generates swagger documentation.
> 
> The code will need to determine whether to create or update a bike, based on whether the bike exists already. The bike should only be determined to exist if there is a bike with a matching serial number registered to the same email (or, to one of a users secondary_emails)
> 
> It will be useful to use SerialNormalizer for matching serial numbers, rather than just using the serial number string - since o and 0 are indistinguishable stamped into metal.

**Comment by sethherr** [comment]
Additional thing I'm thinking now:

If a registration is posted without a serial number, this updated endpoint should only register the bike if there aren't any bikes by the same manufacturer (regardless of what their serial numbers are)

**Comment by stevenbuccini** [comment]
Not sure if I fully understand -- the serial is required on this endpoint, so wouldn't it always be present? Or are you thinking about making it optional?

**Comment by jmromer** [comment]
Related: https://github.com/bikeindex/bike_index/pull/542
