### ISSUE TITLE
Create a new landing page for the Ascend integration

### ISSUE THREAD

**Issue by runt2pb** [bikeindex/bike_index#544]
Using this design: https://www.dropbox.com/sh/tybkggamtbir4rr/AAAHaFI8F4NC0jCA59RH80iAa?dl=0

And this copy:

https://docs.google.com/document/d/10zganWvAeLvDEHLUMFOb8eDIi9GBI-SVmStoNGEywCQ/edit

**Comment by sethherr** [comment]
Resolved by #551
