### ISSUE TITLE
remove orphaned partial (when it's actually orphaned)

### ISSUE THREAD

**Issue by sethherr** [bikeindex/bike_index#636]
During admin revision, @Robertgervais figured out that admin was the only place that used the `bikes/bike` partial - I brought up the issue here: https://github.com/bikeindex/bike_index/pull/629#discussion_r269364568

Once admin has finished being revised and all the existing places that references that partial have been updated to reference the admin partial, we need to remove the `bikes/bike` partial (and preferably, move the `bikes/revised_bike` partial to `bikes/bike` and updated that)

**Comment by Robertgervais** [comment]
`bikes/bike` removed in #728

**Comment by Robertgervais** [comment]
closed with #785
