### ISSUE TITLE
Create Duplicate Bikes controller/displays

### ISSUE THREAD

**Issue by sethherr** [bikeindex/bike_index#709]
I'm not sure when, but the admin duplicate bikes view stopped being useful.

It no longer needs to be on the dashboard, but it still should be accessible, and it should render  something that looks like this:

<img width="1657" alt="Screen Shot 2019-04-22 at 3 51 05 PM" src="https://user-images.githubusercontent.com/1235441/56537928-97160780-6516-11e9-8ccf-ca060f150fe0.png">

**Comment by Robertgervais** [comment]
Closed with #717
