### ISSUE TITLE
Add partial serial searching

### ISSUE THREAD

**Issue by sethherr** [bikeindex/bike_index#734]
There should be a separate method and endpoint for this.

- If someone searches for part of a serial, it should show up on the search page (below the main results, above the "Serial numbers close to"
- `search_close_serials` would need to be modified to exclude partial matches.
- If two or more serials are entered (i.e. the entry is separated by spaces), this should return matches for each individually.

**Comment by Yesh123456** [comment]
We are good to close this @sethherr ?

**Comment by sethherr** [comment]
Yep, good catch @Yesh123456 !
