### ISSUE TITLE
Consider removing should-matchers

### ISSUE THREAD

**Issue by sethherr** [bikeindex/bike_index#795]
I don't think they add very much real test functionality - and they slow down the specs

Our spec suite currently is slow and we need to look for ways to speed it up without sacrificing test utility

**Comment by jmromer** [comment]
Results are in #798 -- definitely helps (~40% decrease). 
I'll take a look at optimizing the slowest-profiling tests too. 
Injecting dependencies / mocking and stubbing more / minimizing db hits should yield some gains too.

**Comment by sethherr** [comment]
I’m wary of mocking and stubbing - it’s easy to test too little. 

If there is low hanging fruit, definitely go for it - if there are tests that seem really slow, or things that are being done that don’t provide much value. But I’d prefer slow tests to tests that don’t cover things or are brittle

**Comment by sethherr** [comment]
Fixed #798
