### ISSUE TITLE
Ambassador organizations have auto unstolen notifications

### ISSUE THREAD

**Issue by sethherr** [bikeindex/bike_index#800]
- We shouldn't create an invoice for all the ambassador organizations, it would add too much noise
- Needs to display on the frontend and also have tests for sending

**Comment by jmromer** [comment]
> Needs to display on the frontend and also have tests for sending

To clarify, by "frontend" do you mean the admin dashboard, organized view or both?

**Comment by sethherr** [comment]
[organized_access_panel.html.haml](https://github.com/bikeindex/bike_index/blob/master/app/views/bikes/_organized_access_panel.html.haml) - not the admin dashboard or one of the organized views.

There is a variable `display_unstolen_notification_form` that is assigned, which covers the view.
