### ISSUE TITLE
Add instagram handle to users

### ISSUE THREAD

**Issue by sethherr** [bikeindex/bike_index#813]
It should have the same options as twitter handle and be editable in the same place ([/edit_my_account?edit_template=sharing](https://bikeindex.org/edit_my_account?edit_template=sharing))

This is full-stack - you'll have to add an migration to add `instagram` to the database and make it behave basically the same as the `twitter` attribute, including adding a form field - but, since you have the twitter attribute as an example it seems pretty approachable.

**Comment by sethherr** [comment]
@parker-erickson - this might be interesting?

**Comment by barefootford** [comment]
@sethherr I'd like to do some work for bike index. This seems like a good first issue to get the app running locally. Fine if I take this?

**Comment by barefootford** [comment]
oh. and @parker-erickson happy to work on this together

**Comment by sethherr** [comment]
This would be a great first thing @barefootford - let me know if you need help with anything!

**Comment by barefootford** [comment]
Sweet. Feel free to assign to me. I should be able to take a stab at it this week. I suspect getting the app up and running will take more time than the PR

**Comment by sethherr** [comment]
Send me an email if you run into troubles seth@bikeindex.org
