### ISSUE TITLE
Selle Anatomica isn't a known manufacturer

### ISSUE THREAD

**Issue by appsforartists** [bikeindex/bike_index#82]
There's no way to add Selle Anatomica as the maker of my saddle.

**Comment by appsforartists** [comment]
Likewise for Cromag

**Comment by sethherr** [comment]
Added Selle Anatomica, and I think you meant Chromag, which is a manufacturer we have, so I'm closing this issue.

**Comment by appsforartists** [comment]
I definitely did.  Don't leave Github issues when you're both tired and on your way out for NYE.  :smiley:
