### ISSUE TITLE
Evaluate migrating from sass to sassc-rails

### ISSUE THREAD

**Issue by jmromer** [bikeindex/bike_index#831]
> Post-install message from sass:

> Ruby Sass has reached end-of-life and should no longer be used.

> * If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install

> * If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  sassc gem: https://github.com/sass/sassc-ruby#readme

> * For more details, please refer to the Sass blog:
  https://sass-lang.com/blog/posts/7828841

**Comment by sethherr** [comment]
~I _think_ this is unnecessary, but it might be a good move depending on how long it will be before we remove css from the asset pipeline.~  Actually - we'll have to keep ruby sass so let's do this! sassc-ruby should be fast and easy, yah?

Additional explanation for why I thought it might not be necessary: https://github.com/bikeindex/bike_index/pull/782 is the correct path - updating the bootstrap gem - but it should be updated to the version that is being used by webpack (I just [added a comment to that PR](https://github.com/bikeindex/bike_index/pull/782/files#r289971194) about this). As soon as it is updated, the css should be moved into the packs files, so ruby sass will largely be unnecessary. But we'll have to keep it around for `premailer-rails`, which inlines our css for our emails from a stylesheet.
