### ISSUE TITLE
Add rubocop-performance 

### ISSUE THREAD

**Issue by jmromer** [bikeindex/bike_index#832]
> Performance Cops will be removed from RuboCop 0.68. Use rubocop-performance gem instead.
> 
> Put this in your Gemfile.
> 
>   gem 'rubocop-performance'
> 
> And then execute:
> 
>   $ bundle install
> 
> Put this into your .rubocop.yml.
> 
>   require: rubocop-performance
> 
> More information: https://github.com/rubocop-hq/rubocop-performance

**Comment by sethherr** [comment]
It's already in there? https://github.com/bikeindex/bike_index/blob/master/.rubocop.yml#L1

I'm closing this. Maybe you meant to put this in a different repository?

**Comment by jmromer** [comment]
That's a head-scratcher, sorry for the noise. I had to re-set-up the repo and I got that warning when bundle installing, not seeing it anymore though. Thanks!
