### ISSUE TITLE
Add Bob to the about page

### ISSUE THREAD

**Issue by sethherr** [bikeindex/bike_index#852]
Similar to #850 - add yourself if you'd like to.

Image should be 500x500 and black and white. Ask in slack if you would like help composing the tagline.

Close this issue if you don't want to be on the about page 🙂

**Comment by Robertgervais** [comment]
:D

**Comment by Robertgervais** [comment]
Text:
Bobby Gervais has had a long history of delivering and carrying stuff on his bike for work and now he's making a living out of helping people recover their bikes. Bobby helps to maintain the Bike Index, and work on new features
