### ISSUE TITLE
Remove Draper decorators

### ISSUE THREAD

**Issue by jmromer** [bikeindex/bike_index#853]
- Remove any empty decorators in `app/decorators`
- Move any cheap-to-refactor methods into helpers
- Add deprecation comment in any remaining decorators and to the Gemfile

**Comment by sethherr** [comment]
This article more articulately explains my feelings about Draper - ["What I dislike about Draper"](https://thepugautomatic.com/2014/03/draper/).

I would be happy with PORO presenters.

**Comment by jmromer** [comment]
I'm fine with avoiding Draper, but just to clarify some terms*:

(*I wonder how many times the phrase "What Rails calls..." has been uttered 🤦‍♂)

The main point in the post seems to be that the author dislikes delegation. It's not so much Draper as the decorator pattern that he dislikes. (Respectable enough, given the bias against OOP that's in vogue at the moment, although I do find it a bit suspect if the alternative in a given context is an even lower complexity-management equilibrium.):

> I'm not a fan of the SimpleDelegator approach, nor of putting a presenter instance in a variable called article, because I feel both of these blur the boundaries and responsibilities of the two objects.

Re. "blur the boundaries and responsibilities of the two objects", rhetorically this is a bit misleading, and substantively, it misses the point. That "blurring" is a feature not a bug. The pattern exists to provide flexibility while maintaining adherence to the single-responsibility principle. The responsibilities between decorator and decorated are separated (concretely, view logic is kept out of the persistence model)—hence the need for delegation. 

(The objection about variable naming—and FUD-mongering expressions like "dark magic", etc—can be safely ignored, in my opinion.)

The alternative he proposes of wrapping a persistence model with another object (I'm avoiding saying PORO—there's an implicit appeal to purity there) is similar to a [facade](https://en.wikipedia.org/wiki/Facade_pattern). With that approach we'll have to either manually pass along any messages sent from a template to the persistence model being wrapped (and update the implementation of the facade as those needs change), or pass both a model instance and its "decorator" (facade) to the template separately and potentially invoke methods on them separately, as suggested in the blog post:

```erb
<h1><%= @article.title %></h1> 
<p><%= @article_presenter.published_at(self) %></p>
```

A facade-based view / view model layer (claim: [Rails templates are not a view layer](https://github.com/drapergem/draper#why-use-a-decorator)) is _interesting_, but... I'm concerned that setting off on an idiosyncratic direction here will almost certainly generate opportunity costs (in the form of work we could theoretically avoid because it reproduces what's available elsewhere) with no offsetting benefit. (e.g., What does this approach look like when we want to wrap multiple elements in a collection? Maybe we write a convenience method. Can we generalize and use that method elsewhere? Maybe we make a base class to share it among different subclasses of presenter, dot dot dot, we have a facade-based Draper-alternative).

At least, I don't see a clear rationale for taking on that work, so I think the approach discussed offline — using Rails's helpers instead — makes the most sense, at least for now. Happy to revisit if we feel a compelling need to down the line, though.

**Comment by sethherr** [comment]
I also dislike delegation 😉 .

I think the object naming _is_ a big part of my problem. If we switched to variables that acknowledged the objects were decorated, I wouldn't really have a problem - ie `@bike_decorated` instead of just `@bike` (but I don't see much of a problem having to use `object` in decorators). I like things being the things they're called.

I still prefer using helpers, if possible. I think part of this is also my preference for doing things "the Rails way". Modifying how Rails works, in my experience, leads to headaches. It's better to figure out a way to do whatever you're doing in the Rails way - and if that is unacceptable, opt out of touching Rails at all.
