### ISSUE TITLE
Commenting

### ISSUE THREAD

**Issue by sethherr** [bikeindex/bike_index#9]
We need our own commenting system.

**Requirements**
- It should email messages to users when someone comments on their bike.
- It should allow threading
- It should load via an AJAX call, so that things can still be cached.
- Users should be able to turn off comments on their bike.

**Comment by digitalcake** [comment]
Whats your thoughts about using acts as commentable? https://github.com/elight/acts_as_commentable_with_threading/tree/1.2.x

**Comment by sethherr** [comment]
I'm totally into it! I have used acts as commentable before and I think it's good.

I still am committed to loading them with Ajax, so it would need an API route.

**Comment by sethherr** [comment]
[discuss.bikeindex.org](https://discuss.bikeindex.org/) resolves this
