### ISSUE TITLE
Fix ambassador leaderboard counts

### ISSUE THREAD

**Issue by sethherr** [bikeindex/bike_index#908]
![F14704FB-A189-48E6-B1F7-C504B9BF60D8](https://user-images.githubusercontent.com/1235441/59621894-17a34f80-90e5-11e9-990c-59b0c3a419f5.png)

**Comment by jmromer** [comment]
@sethherr Looks like a data issue -- bulk insert seems to be creating duplicate assignments. 

Deduping with the following

```rb
keep_ids = AmbassadorTaskAssignment.group('user_id, ambassador_task_id').pluck('max(id)')

AmbassadorTaskAssignment.where.not(id: keep_ids).find_in_batches(batch_size: 100) {|id_batch| AmbassadorTaskAssignment.where(id: id_batch).delete_all }
```

debugging the after_create jobs...

**Comment by jmromer** [comment]
```rb
AmbassadorTaskAssignment.group('user_id, ambassador_task_id').pluck('count(id)').uniq
# => [1]
```
