### ISSUE TITLE
Honeybadger fail

### ISSUE THREAD

**Issue by sethherr** [bikeindex/bike_index#935]
Currently, because the Theft Alert controller added manual calls to Honeybadger, we need to have Honeybadger in all our environments.

Unfortunately, for reasons I can't fathom and haven't investigated deeply, if it isn't in the production group it doesn't alert on errors in production.

How I tested this:

Going in to console, running a job that threw an error, watched it fail in the sidekiq admin panel. Never received an alert for it in Honeybadger.

Shipped b2d4e957b5507c69879beb391bffb49e11332986 - did the same thing and received and alert.

I'm not sure why the Honeybadger call needs to be done in the controller - I feel like it could probably raise if it raises and we'll get notified (and rescue just `Stripe::CardError`, as done in the payments controller, where there is no need to notify). 

Or we could investigate why Honeybadger isn't working and solve that.

**Comment by jmromer** [comment]
> Unfortunately, for reasons I can't fathom and haven't investigated deeply, if it isn't in the production group it doesn't alert on errors in production.

My hunch is this may have been caused by cached gems rather than the gem group (I saw the failure locally too until I killed the previous version's binary), but it's probably overkill notify manually there anyway, here's a quick fix: #936

**Comment by sethherr** [comment]
Oooh. That makes sense.

I'm happy not investigating this more, if you believe the manual notification is overkill and we don't need it
