### ISSUE TITLE
Bundle FontAwesome with Yarn

### ISSUE THREAD

**Issue by jmromer** [bikeindex/bike_index#981]
Move FA bundling into Yarn:

```html
-# app/views/layouts/application_revised.html.haml L8-9 (fbf517f6)

<!-- TODO: Use yarn -->
<script src="https://kit.fontawesome.com/82eb17360c.js"></script>
```
<sup>[[source](https://github.com/bikeindex/bike_index/blob/fbf517f6/app/views/layouts/application_revised.html.haml#L8-L9)]</sup>

1. [Bundle with yarn](https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers)
2. Include in layouts
  a. ?
4. Ship it

**Comment by sethherr** [comment]
I think we've decided this is low value and doesn't need to be done any time soon, so I'm closing this issue
